# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luis Alfonso Ortiz Perez
title: Estudiante ingeneria en computacion
email: luisalf.ortizp@gmail.com
website: https://github.com/Huicho01425

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  Huicho01425
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: 
linkedin_username: LuisAlfOrtiz
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:

  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Enaitech
        link: enaitech.com
        # link_text: boringcompany.com
        sub_title: Soporte tecnico 
        caption: Enero 2019 - Noviembre 2019
        quote: >
          empresa dedicada a solucines en tecnologias, redes y telefonia.
        description: | # this will include new lines to allow paragraphs
            Instalación, Soporte técnico de equipos de cómputo y redes 
            Atención a tickets (contacto con clientes y proveedores).

  - title: Educacion # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: C. U. de Cs. Exactas e Ingenerías  UDG
        caption: 2020 - Presente
        sub_title: Ingeniería en Computación.
        quote: >
          Atiende las necesidades de la sociedad en la formación de educación superior e investigación científica y tecnológica en el campo de las ciencias exactas e ingenierías, impulsa la vinculación, la extensión y la difusión de la cultura, con carácter multidisciplinar, global y humanista, genera soluciones sostenibles, pertinentes e innovadoras mediante la excelencia académica, equidad, inclusión, integridad, solidaridad, transparencia y rendición de cuentas, con responsabilidad y compromiso social.
        description: | # this will include new lines to allow paragraphs
          Conocimientos en las áreas algoritmos de computación, de diseño de software, de arquitectura de computadoras y de redes que integran paradigmas modernos de cómputo y tecnologías emergentes.
      
      - layout: left
        title: Escuela Politecnica "Ing. Jorge Matute Remus" UDG
        caption: 2015 - 2019
        sub_title: Tecnologo Profesional en Informatica
        quote: >
          Escuela formadora de recursos humanos, en áreas de innovación y gestión de desarrollo en los Bachilleratos Tecnológicos y Carreras de Tecnólogos Profesionales, presentando a la sociedad profesionistas especializados en cada una de las áreas disciplinares que se ofertan.
        description: | # this will include new lines to allow paragraphs
          Ensambla, opera y da mantenimiento a equipos de cómputo de sistemas informáticos; capacita y entrena a usuarios en el uso de equipos y programas informáticos; instala y coordina el uso de redes de cómputo y periféricos de sistemas informáticos; desarrolla y modifica programas informáticos y páginas web; gestiona la creación de microempresas, supervisa y da seguimiento en los aspectos contables y administrativos.
    

  - title: Un poco mas de este ser
    layout: text
    content: | # this will include new lines to allow paragraphs
      Aparte de tener interes en la tecnologia, mis pasatiempos son:
      - Jugar videojuegos.
      - Ver videos de entretenimiento.
      - Entretenimientos sociales.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
